import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  buildCheckPlan,
  loadCheckManifest,
  renderCheckInventory,
  renderCheckPlan,
  resolveGateTarget,
  runDoctor,
} from "../../../packages/check-orchestrator/src";

describe("check orchestrator manifest", () => {
  const manifest = loadCheckManifest();

  it("mirrors the current root scripts without doctor errors", () => {
    expect(manifest.gates.length).toBeGreaterThan(150);
    expect(runDoctor(manifest).filter((diagnostic) => diagnostic.severity === "error")).toEqual([]);
  });

  it("assigns stable ids for representative scopes", () => {
    expect(resolveGateTarget(manifest, "rust/selected-query/consumers")?.scriptName).toBe(
      "check:rust-selected-query-consumers",
    );
    expect(resolveGateTarget(manifest, "ts7/phase-b/protocol@tsgo")?.scriptName).toBe(
      "check:ts7-phase-b-protocol-tsgo",
    );
    expect(resolveGateTarget(manifest, "ts7/phase-c/watch@tsgo")?.scriptName).toBe(
      "check:ts7-phase-c-watch-tsgo",
    );
    expect(resolveGateTarget(manifest, "tsgo/release-batch")?.scriptName).toBe(
      "check:release-batch-tsgo",
    );
    expect(resolveGateTarget(manifest, "tsgo/real-project-corpus")?.scriptName).toBe(
      "check:real-project-corpus-tsgo",
    );
    expect(resolveGateTarget(manifest, "tsgo/lsp-server-smoke")?.scriptName).toBe(
      "check:lsp-server-smoke-tsgo",
    );
    expect(resolveGateTarget(manifest, "tsgo/release/bundle")?.scriptName).toBe(
      "check:tsgo-release-bundle",
    );
    expect(resolveGateTarget(manifest, "tooling/orchestrator-doctor")?.scriptName).toBe(
      "check:orchestrator-doctor",
    );
    expect(resolveGateTarget(manifest, "tooling/orchestrator-inventory")?.scriptName).toBe(
      "check:orchestrator-inventory",
    );
    expect(
      resolveGateTarget(manifest, "release/check/packaged-engine-shadow-runner")?.scriptName,
    ).toBe("check:packaged-engine-shadow-runner");
    expect(
      resolveGateTarget(manifest, "release/check/packaged-engine-shadow-runner-matrix")?.scriptName,
    ).toBe("check:packaged-engine-shadow-runner-matrix");
    expect(
      resolveGateTarget(manifest, "release/check/packaged-selected-query-default")?.scriptName,
    ).toBe("check:packaged-selected-query-default");
  });

  it("tracks bundle script references", () => {
    const releaseBundle = resolveGateTarget(manifest, "rust/release/bundle");
    expect(releaseBundle?.kind).toBe("bundle");
    expect(releaseBundle?.referencedScripts).toContain("check:rust-workspace");
    expect(releaseBundle?.referencedScripts).toContain("check:rust-producer-boundary");

    const releaseVerify = resolveGateTarget(manifest, "release/release/verify");
    expect(releaseVerify?.kind).toBe("bundle");
    expect(releaseVerify?.referencedScripts).toEqual(
      expect.arrayContaining([
        "check",
        "check:plugin-consumer-example",
        "check:plugin-consumers",
        "check:rust-release-bundle",
        "check:tsgo-release-bundle",
        "package",
        "test",
      ]),
    );
  });

  it("renders a deterministic check inventory", () => {
    const inventory = renderCheckInventory(manifest);
    expect(inventory).toContain("# Check Inventory");
    expect(inventory).toContain("Generated by `pnpm cme-check inventory --write`");
    expect(inventory).toMatch(/\| Scope\s+\| Gates \| Bundles \| Aliases \| Commands \|/);
    expect(inventory).toMatch(
      /\| `tsgo\/release\/bundle`\s+\| alias\s+\| `check:tsgo-release-bundle`\s+\|/,
    );
    expect(inventory).toMatch(
      /\| `rust\/release\/bundle`\s+\| bundle\s+\| `check:rust-release-bundle`\s+\|/,
    );
  });

  it("builds a readable nested plan for aggregate gates", () => {
    const target = resolveGateTarget(manifest, "release/release/verify");
    expect(target).toBeTruthy();

    const plan = buildCheckPlan(manifest, target!);
    expect(plan.steps[0]?.scriptName).toBe("release:verify");
    expect(plan.steps).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          depth: 1,
          scriptName: "check:rust-release-bundle",
        }),
        expect.objectContaining({
          depth: 1,
          scriptName: "check:tsgo-release-bundle",
        }),
        expect.objectContaining({
          scriptName: "build",
        }),
      ]),
    );

    const rendered = renderCheckPlan(plan);
    expect(rendered).toContain("Check plan: release/release/verify (release:verify)");
    expect(rendered).toContain("- release/release/verify (release:verify, bundle)");
    expect(rendered).toContain("  - rust/release/bundle (check:rust-release-bundle, bundle)");
  });

  it("reports workflow direct script calls that bypass cme-check", () => {
    const root = mkdtempSync(path.join(os.tmpdir(), "cme-check-orchestrator-"));
    mkdirSync(path.join(root, ".github/workflows"), { recursive: true });
    writeFileSync(
      path.join(root, "package.json"),
      JSON.stringify(
        {
          name: "css-module-explainer",
          scripts: {
            "cme-check": "node ./check.js",
            check: "echo check",
            test: "echo test",
          },
        },
        null,
        2,
      ),
    );
    writeFileSync(
      path.join(root, ".github/workflows/ci.yml"),
      [
        "name: CI",
        "jobs:",
        "  direct:",
        "    steps:",
        "      - run: pnpm check",
        "      - run: pnpm cme-check run test",
      ].join("\n"),
    );

    const diagnostics = runDoctor(loadCheckManifest(root));
    expect(diagnostics).toEqual([
      expect.objectContaining({
        severity: "error",
        code: "workflow-direct-script-call",
        message: expect.stringContaining(
          '.github/workflows/ci.yml:5 calls "check" directly; use "pnpm cme-check run core/check".',
        ),
      }),
    ]);
  });

  it("reports invalid cme-check targets before CI reaches runtime", () => {
    const root = mkdtempSync(path.join(os.tmpdir(), "cme-check-orchestrator-"));
    mkdirSync(path.join(root, ".github/workflows"), { recursive: true });
    writeFileSync(
      path.join(root, "package.json"),
      JSON.stringify(
        {
          name: "css-module-explainer",
          scripts: {
            "cme-check": "node ./check.js",
            check: "echo check",
            "release:verify": "pnpm cme-check bundle check",
            test: "echo test",
          },
        },
        null,
        2,
      ),
    );
    writeFileSync(
      path.join(root, ".github/workflows/ci.yml"),
      [
        "name: CI",
        "jobs:",
        "  invalid:",
        "    steps:",
        "      - run: pnpm cme-check run missing-target",
      ].join("\n"),
    );

    const diagnostics = runDoctor(loadCheckManifest(root));
    expect(diagnostics).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          severity: "error",
          code: "non-bundle-cme-check-target",
          message: 'Script "release:verify" uses cme-check bundle for non-bundle target "check".',
        }),
        expect.objectContaining({
          severity: "error",
          code: "workflow-unknown-cme-check-target",
          message: expect.stringContaining(
            '.github/workflows/ci.yml:5 references unknown cme-check target "missing-target".',
          ),
        }),
      ]),
    );
  });
});
