import type { CheckGate, CheckManifest, CheckScopeId } from "./types";

const SCOPE_ORDER: readonly CheckScopeId[] = [
  "core",
  "release",
  "tsgo",
  "ts7",
  "rust",
  "plugin",
  "contract",
  "editor",
  "test",
  "workspace",
  "tooling",
];

export function renderCheckInventory(manifest: Pick<CheckManifest, "gates">): string {
  const gates = [...manifest.gates].toSorted((left, right) => {
    const scopeOrder = scopeIndex(left.scope) - scopeIndex(right.scope);
    return scopeOrder || left.id.localeCompare(right.id);
  });

  return [
    "# Check Inventory",
    "",
    "Generated by `pnpm cme-check inventory --write`. Do not edit manually.",
    "",
    `Total gates: ${gates.length}`,
    "",
    "## Scope Summary",
    "",
    renderMarkdownTable(
      ["Scope", "Gates", "Bundles", "Aliases", "Commands"],
      renderScopeSummary(gates),
      ["left", "right", "right", "right", "right"],
    ),
    "",
    ...SCOPE_ORDER.flatMap((scope) => renderScopeSection(scope, gates)),
  ]
    .join("\n")
    .trimEnd();
}

function renderScopeSummary(gates: readonly CheckGate[]): string[][] {
  return SCOPE_ORDER.map((scope) => {
    const scopeGates = gates.filter((gate) => gate.scope === scope);
    const bundles = scopeGates.filter((gate) => gate.kind === "bundle").length;
    const aliases = scopeGates.filter((gate) => gate.kind === "alias").length;
    const commands = scopeGates.filter((gate) => gate.kind === "command").length;
    return [scope, String(scopeGates.length), String(bundles), String(aliases), String(commands)];
  }).filter(([, gateCount]) => gateCount !== "0");
}

function renderScopeSection(scope: CheckScopeId, gates: readonly CheckGate[]): string[] {
  const scopeGates = gates.filter((gate) => gate.scope === scope);
  if (scopeGates.length === 0) return [];

  return [
    `## ${scope}`,
    "",
    renderMarkdownTable(
      ["ID", "Kind", "Script", "References"],
      scopeGates.map((gate) => [
        formatCode(gate.id),
        gate.kind,
        formatCode(gate.scriptName),
        formatRefs(gate.referencedScripts),
      ]),
      ["left", "left", "left", "left"],
    ),
    "",
  ];
}

function formatRefs(referencedScripts: readonly string[]): string {
  if (referencedScripts.length === 0) return "";
  return referencedScripts.map(formatCode).join(", ");
}

function formatCode(value: string): string {
  return `\`${escapeMarkdown(value)}\``;
}

function escapeMarkdown(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("`", "\\`");
}

type ColumnAlignment = "left" | "right";

function renderMarkdownTable(
  headers: readonly string[],
  rows: readonly (readonly string[])[],
  alignments: readonly ColumnAlignment[],
): string {
  const widths = headers.map((header, index) =>
    Math.max(3, header.length, ...rows.map((row) => row[index]?.length ?? 0)),
  );

  return [
    renderTableRow(headers, widths, alignments, true),
    renderSeparatorRow(widths, alignments),
    ...rows.map((row) => renderTableRow(row, widths, alignments, false)),
  ].join("\n");
}

function renderTableRow(
  cells: readonly string[],
  widths: readonly number[],
  alignments: readonly ColumnAlignment[],
  isHeader: boolean,
): string {
  return `| ${widths
    .map((width, index) => {
      const cell = cells[index] ?? "";
      if (!isHeader && alignments[index] === "right") {
        return cell.padStart(width);
      }
      return cell.padEnd(width);
    })
    .join(" | ")} |`;
}

function renderSeparatorRow(
  widths: readonly number[],
  alignments: readonly ColumnAlignment[],
): string {
  return `| ${widths
    .map((width, index) =>
      alignments[index] === "right" ? `${"-".repeat(width - 1)}:` : "-".repeat(width),
    )
    .join(" | ")} |`;
}

function scopeIndex(scope: CheckScopeId): number {
  const index = SCOPE_ORDER.indexOf(scope);
  return index === -1 ? SCOPE_ORDER.length : index;
}
