export type {
  Position,
  Range,
  StyleLang,
  ComposesRef,
  SelectorInfo,
  ScssClassMap,
  CxBinding,
  // Wave 1: unified ClassRef model
  ClassRef,
  ClassRefOrigin,
  StaticClassRef,
  TemplateClassRef,
  VariableClassRef,
  ResolvedType,
  CallSite,
  CallSiteMatch,
  CallSiteExpansion,
  ShowReferencesArgs,
  ShowReferencesLocation,
} from "./types";
